library(zoo)
library(sandwich)
library(urca)
library(lmtest)
library(vars)
full <- read.csv("fullseries.csv")
model1 = VAR(full[,c(-1,-2,-5,-6,-7,-8)], p = 2, type = "both")
model2 = VAR(full[-1:-48,c(-1,-2,-7,-8)], p = 2, type = "both")
model3 = VAR(full[-1:-66,c(-1,-2)], p = 2, type = "both")
summary(model1)